server:
  port: 8885

spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      enabled: true

    gateway:
      routes:
        - id: chatgptai-service
          uri: lb://chatgptai-service
          predicates:
            - Path=/api/v1/ai/request/**
